# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d34d2a4c001de40f10b935e23d41e1c6c364bfeeacbec305802f99d29661cfa9a5ac46137245b80966e9aae1fb1deb4f20fcd98e2059b9980e151ea168925ba

test:
  secret_key_base: 9efb417b3c773a2b9e9ebc95841f99f355f3f0f0dccd9790328d326a2ba5b1e1c2549ef76de7196d7bafaf2e5a72e0e20e8e8794309360d9af9f1c0ed623971e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
